### PR TITLE
Add Js colors

### PR DESCRIPTION
**Pull request by Ajnasz**
See js syntax file at https://github.com/pangloss/vim-javascript

### CODE REVIEW

**Comment by KabbAmine** [comment]
Thanks for your contribution, but can you provide me a before/after screenshots to compare? (I'am using another js syntax plugin).

Also, on my local version, I've assigned the color `lightGreen` to `String` group, so by idea the groups `jsStringS` & `jsStringD` will inherit the color, you can then remove them.

**Comment by Ajnasz** [comment]
Hi!

Thank you for the response!

This is the before screenshot:
https://dl.dropboxusercontent.com/u/6566973/Screenshots/shot-2015-10-06-132447.png
This is the after screenshot:
https://dl.dropboxusercontent.com/u/6566973/Screenshots/shot-2015-10-06-132331.png

I also removed the jsString definitions

Thanks

On Tue, Oct 6, 2015 at 12:59 PM, KabbAmine notifications@github.com wrote:

> Thanks for your contribution, but can you provide me a before/after
> screenshots to compare? (I'am using another js syntax plugin).
> 
> Also, on my local version, I've assigned the color lightGreen to String
> group, so by idea the groups jsStringS & jsStringD will inherit the
> color, you can then remove them.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KabbAmine/yowish.vim/pull/2#issuecomment-145822444.

## 

Koszti Lajos

**Comment by KabbAmine** [comment]
Looks good for me apart for the functions, I think that violet doesn't render very well. A  blueish color will be more appropriate.

Anyway, I'm changing a lot of things now in the theme, so we'll wait until things are done to look more further at your js implementation, then I'll merge your PR, are you ok with that?

**Comment by Ajnasz** [comment]
Great, thank you!

On Tue, Oct 6, 2015 at 1:46 PM, KabbAmine notifications@github.com wrote:

> Looks good for me apart for the functions, I think that violet doesn't
> render very well. A blueish color will be more appropriate.
> 
> Anyway, I'm changing a lot of things now in the theme, so we'll wait until
> things are done to look more further at your js implementation, then I'll
> merge your PR, are you ok with that?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KabbAmine/yowish.vim/pull/2#issuecomment-145832519.

## 

Koszti Lajos

**Comment by KabbAmine** [comment]
Unfortunately, after refactoring and to have a certain sameness between colors of different js syntax plugins, I've chosen another colors than the ones used in your PR.

Check by yourself (And yes I've re-write your code sample :smile:).
yowish-js

Doing that, your PR is no more needed :no_mouth:, but please let me know what you think about [the result](https://github.com/KabbAmine/yowish.vim/tree/dev-js) in #3 

Thanks for your contribution.

**Pull request closed without merging**
